apiVersion: v1
kind: Pod
metadata: 
  name: pod1
#  namespace: black
  labels:
    app: myapp 
spec: 
  containers: 
  - name: coin 
    image: nginx
    imagePullPolicy: Never 
    resources: 
      requests: 
        memory: "250M"
        cpu: "0.1"
      limits: 
        cpu: "0.5"
        memory: "700M"
