apiVersion: v1 
kind: Pod 
metadata: 
  name: api-pod
spec: 
  containers: 
  - image: centos:7
    name: shell 
    command: 
      - "/bin/bash"
      - "-c"
      - "sleep 1000"
    volumeMounts: 
      - name: vol
        mountPath: "/tmp/apikey"
        readOnly: true 
  volumes: 
  - name: vol
    secret: 
      secretName: apikey



