apiVersion: v1
kind: Pod
metadata: 
  name: pod4
#  namespace: black
  labels:
    app: myapp 
spec: 
  containers: 
  - name: coin 
    image: nginx
    imagePullPolicy: Never 
    resources: 
      requests: 
        memory: 250Mi
        cpu: 100m 
      limits: 
        cpu: 500m
        memory: 250Mi
