apiVersion: v1 
kind: Pod
metadata: 
  name: d1 
spec: 
  containers:
  - name: test
    image: nginx
    volumeMounts:
    - name: pv0001
      mountPath: "/var/www/html"

  volumes: 
  - name: pv0001
    persistentVolumeClaim: 
      claimName: nfsclaim
