apiVersion: v1 
kind: PersistentVolume 
metadata: 
  labels: 
    volume: pv0001
  name: pv0001 
spec: 
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 5Gi 
  claimRef: 
    apiVersion: v1   
    kind: PersistentVolumeClaim
    name: myclaim
    namespace: default
  hostPath: 
    path: /mnt/pv-data/pv0001
    type: ""
  persistentVolumeReclaimPolicy: Recycle 
  volumeMode: Filesystem
status: 
  phase: Bound 
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: myclaim 
spec: 
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests: 
      storage: 1Gi 
