apiVersion: v1
kind: Pod
metadata:
  name: nvolpod
spec:
  containers:
    - name: test
      image: nginx:latest
      volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: nfsclaim
