apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    volumeMounts: 
    - mountPath: "/var/www/html"
      name: pv
  volumes:
    - name: pv 
      persistentVolumeClaim: 
        claimName: nfsclaim
